FROM node:24-bookworm-slim

WORKDIR /app

RUN apt-get update && apt-get install -y openssl && rm -rf /var/lib/apt/lists/*

COPY package.json package-lock.json* ./
RUN npm ci

COPY prisma ./prisma
COPY src ./src
COPY tsconfig.json ./
COPY docker-entrypoint.dev.sh ./

RUN npx prisma generate

ENV NODE_ENV=development

CMD ["sh", "./docker-entrypoint.dev.sh"]
